In [3]:
import torch
import numpy as np

In [8]:
save = torch.full((1, 6, 1), np.nan, dtype=torch.float32)
values = torch.tensor([1, 2, 4, 6], dtype=torch.float32).view(1, 4, 1)
index = [0, 1, 3, 5]

In [5]:
save

tensor([[[nan],
         [nan],
         [nan],
         [nan],
         [nan],
         [nan]]])

In [7]:
values

tensor([[[1.],
         [2.],
         [4.],
         [6.]]])

In [9]:
save.scatter_(1, torch.tensor(index).reshape(1, -1, 1), values)

tensor([[[1.],
         [2.],
         [nan],
         [4.],
         [nan],
         [6.]]])

In [10]:
save.reshape(1, 2, 3)

tensor([[[1., 2., nan],
         [4., nan, 6.]]])